import { readFile, readdir, writeFile } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import { execFileSync } from 'node:child_process';
import { chromium } from '@playwright/test';
import { preview } from 'vite';
import assert from 'node:assert/strict';
import { buildShell } from '../src/host/build.ts';
import { recordFlowEvidence } from '../tests/helpers/evidence.ts';

const root=resolve('experiments/generated/performance-browser');const built=await buildShell(root);
await writeFile(join(root,'bench.html'),'<!doctype html><meta charset="utf-8"><title>Atseq worker measurement</title><button id="respond">Check responsiveness</button><p id="status">Measured replay runs in a worker.</p>');
const worker='/assets/'+(await readdir(join(root,'assets'))).find(name=>/^worker-.*\.js$/.test(name));
const server=await preview({root,build:{outDir:root},logLevel:'silent',preview:{host:'127.0.0.1',port:0}}),browser=await chromium.launch(),page=await browser.newPage();const browserCdp=await browser.newBrowserCDPSession();
const measurements:any[]=[];
async function rss(){const processes=await browserCdp.send('SystemInfo.getProcessInfo');return processes.processInfo.reduce((sum:any,p:any)=>{try{return sum+Number(execFileSync('ps',['-o','rss=','-p',String(p.id)],{encoding:'utf8'}).trim())*1024;}catch{return sum;}},0);}
try{
  await page.addInitScript({content:'globalThis.__name = (value) => value;'});
  await page.goto(server.resolvedUrls!.local[0]!+'bench.html');
  for(const size of [100,1000,10000]){
    const input=JSON.parse(await readFile(`experiments/generated/performance/input-${size}.json`,'utf8')),before=await rss();
    const loaded=await page.evaluate(async worker=>{
      const w=window as any;w.runtime?.terminate();w.runtime=new Worker(worker,{type:'module'});w.responses=new Map();w.counter=0;w.clicks=0;
      document.querySelector<HTMLButtonElement>('#respond')!.onclick=()=>{w.clicks++;};
      w.runtime.onmessage=({data}:any)=>{const done=w.responses.get(data.id);if(done){w.responses.delete(data.id);data.error?done.reject(new Error(data.error.message)):done.resolve(data.result);}};
      w.call=(kind:string,args:any={})=>new Promise((resolve,reject)=>{const id=++w.counter;w.responses.set(id,{resolve,reject});w.runtime.postMessage({id,kind,...args});});
      const start=performance.now();await w.call('reset');return performance.now()-start;
    },worker);
    await page.evaluate(input=>{const w=window as any;w.ticks=0;w.maxGap=0;w.lastTick=performance.now();w.ticking=true;const tick=()=>{if(!w.ticking)return;const now=performance.now();w.maxGap=Math.max(w.maxGap,now-w.lastTick);w.lastTick=now;w.ticks++;requestAnimationFrame(tick);};requestAnimationFrame(tick);w.started=performance.now();w.done=false;w.run=w.call('sync',{invitation:{app:input.genesis.app,genesis:input.genesisCid},input}).then((snapshot:any)=>{w.elapsed=performance.now()-w.started;w.ticking=false;w.done=true;w.snapshot=snapshot;return snapshot;});},input);
    await page.getByRole('button',{name:'Check responsiveness'}).click();
    const measured=await page.evaluate(async()=>{const w=window as any;const snapshot=await w.run;return {elapsedMs:w.elapsed,ticks:w.ticks,maxAnimationGapMs:w.maxGap,clicks:w.clicks,position:snapshot.projection.frontier.position,selected:snapshot.projection.state.selected,stalled:snapshot.stalled??null};});
    assert.equal(measured.position,size);assert.equal(measured.selected,String(size));assert.equal(measured.stalled,null);assert.equal(measured.clicks,1);assert.ok(measured.ticks>0);
    const result={size,workerLoadMs:loaded,fullReplayAndTransferMs:measured.elapsedMs,animationFrames:measured.ticks,maxAnimationGapMs:measured.maxAnimationGapMs,responsivenessClickObserved:true,browserRssBefore:before,browserRssAfter:await rss()};measurements.push(result);console.log(JSON.stringify(result));
  }
  await recordFlowEvidence('browser-performance',measurements.map(m=>({name:`browser history ${m.size}`,passed:true,elapsedMs:m.fullReplayAndTransferMs})),{expectedCases:3,browserVersion:browser.version(),measurements,shellAssets:built.files,memoryMethod:'Sum of RSS for the isolated Chromium process IDs returned by SystemInfo.getProcessInfo, from ps. Includes shared pages counted by each process; not retained JavaScript heap and not additive per application.',timingMethod:'One cold worker per size. Worker load is creation to first reset reply. Replay includes postMessage copies and returned projection. Browser cache may be warm; source data generated by the PDS measurement.'});
}finally{await browser.close();await new Promise<void>(done=>server.httpServer.close(()=>done()));}
